[[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 4

[[main]]
  identifier = "archive"
  name = "归档"
  url = "archive"
  weight = 3

[[main]]
  identifier = "posts"
  name = "文章"
  url = "posts"
  weight = 1
[[main]]
  identifier = "comments"
  name = "评论"
  url = "comments"
  weight = 2
